apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Values.AppName }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.AppName }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.AppName }}
      tag: {{ .Values.image.tag }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.AppName }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          protocol: {{ .Values.service.protocol }}
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.path }}
             port: {{ .Values.livenessProbe.httpGet.port }}
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe.path }}
             port: {{ .Values.readinessProbe.httpGet.port }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.memory }}