apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prob
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prob.yaml
    path: helm
    repoURL: https://github.com/hanWang729/TechTrends.git
    targetRevision: HEAD

